# Generated by Django 4.2.7 on 2025-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='color',
            field=models.CharField(choices=[('#009885', 'Verde'), ('#C90166', 'Rosa'), ('#AE192D', 'Rojo'), ('#ff6b35', 'Naranja'), ('#6c757d', 'Gris'), ('#0052cc', 'Azul'), ('#6f42c1', 'Morado'), ('#e83e8c', 'Fucsia')], default='#009885', max_length=7),
        ),
    ]
