version: '3.8'

services:
  web:
    build: .
    ports:
      - "3019:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_SETTINGS_MODULE=gestion_eventos_salas.settings_docker
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gestion_salas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: