version: '3.8'

services:
  web:
    build: .
    ports:
      - "3019:8000"
    volumes:
      - sqlite_data:/app
    environment:
      - DJANGO_SETTINGS_MODULE=gestion_eventos_salas.settings_docker
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gestion_salas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Puerto diferente para evitar conflicto

volumes:
  sqlite_data:
  postgres_data: